### PR TITLE
Fix force unwrap in ASN.1 UTCTime parsing, add use of en_US_POSIX locale

### PR DESCRIPTION
**Pull request by RockyYara**

### CODE REVIEW

**Comment by RockyYara** [comment]
Added use of special universal locale for correct UTCTime parsing.
This is needed if user for example has French locale and 12-hours time format.

**Comment by kdubb** [comment]
@RockyYara Thank you for the PR! I had to disable a CI job that needed auth crews to complete but it's working now for you.

Any chance you can add unit tests that test UTCTime endoing/decoding. I believe there are tests in `ASN1Tests.swift` for `GeneralizedTime` encoding/decoding that you could copy or take inspiration from. Adding them to the `ASN1Tests` test suite would be great.

**Comment by RockyYara** [comment]
@kdubb Welcome!

Yes, I think I can add them in some time. Maybe you can push updated project file with added target for unit tests?

**Comment by kdubb** [comment]
@RockyYara The unit tests are already included as part of the Swift Package. Opening the Swift Package in Xcode will create a test target automatically.

**Comment by kdubb** [comment]
@RockyYara There were other issues with UTC time formatting & parsing. I've opened a new PR #20 that removes the force unwrap and parses times according to ASN.1 spec.

**Comment by RockyYara** [comment]
@kdubb Thanks a lot for your work!

**Pull request closed without merging**
